set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER ${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-g++)

set(CMAKE_SYSROOT /usr/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu)

include(${CMAKE_CURRENT_LIST_DIR}/find_root.cmake)
